// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

// arms
SEXP arms(NumericVector xinit, double xl, double xr, Function lpdf, double convex, int npoint, int dometrop, double xprev, int nsamp, int include_neval);
RcppExport SEXP _armspp_arms(SEXP xinitSEXP, SEXP xlSEXP, SEXP xrSEXP, SEXP lpdfSEXP, SEXP convexSEXP, SEXP npointSEXP, SEXP dometropSEXP, SEXP xprevSEXP, SEXP nsampSEXP, SEXP include_nevalSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type xinit(xinitSEXP);
    Rcpp::traits::input_parameter< double >::type xl(xlSEXP);
    Rcpp::traits::input_parameter< double >::type xr(xrSEXP);
    Rcpp::traits::input_parameter< Function >::type lpdf(lpdfSEXP);
    Rcpp::traits::input_parameter< double >::type convex(convexSEXP);
    Rcpp::traits::input_parameter< int >::type npoint(npointSEXP);
    Rcpp::traits::input_parameter< int >::type dometrop(dometropSEXP);
    Rcpp::traits::input_parameter< double >::type xprev(xprevSEXP);
    Rcpp::traits::input_parameter< int >::type nsamp(nsampSEXP);
    Rcpp::traits::input_parameter< int >::type include_neval(include_nevalSEXP);
    rcpp_result_gen = Rcpp::wrap(arms(xinit, xl, xr, lpdf, convex, npoint, dometrop, xprev, nsamp, include_neval));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_armspp_arms", (DL_FUNC) &_armspp_arms, 10},
    {NULL, NULL, 0}
};

RcppExport void R_init_armspp(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
