# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

.arms_gibbs2 <- function(nSamples, previous, logPdf, lower, upper, initial, convex, maxPoints, metropolis, includeNEvaluations) {
    .Call('_armspp_arms_gibbs2', PACKAGE = 'armspp', nSamples, previous, logPdf, lower, upper, initial, convex, maxPoints, metropolis, includeNEvaluations)
}

.arms_gibbs <- function(nSamples, xPrevious, logPdf, xLower, xUpper, xInitial, convex, maxPoints, metropolis) {
    .Call('_armspp_arms_gibbs', PACKAGE = 'armspp', nSamples, xPrevious, logPdf, xLower, xUpper, xInitial, convex, maxPoints, metropolis)
}

.arms <- function(xInitial, xl, xr, lpdf, convex, npoint, dometrop, xprev, arguments, nsamp, include_neval) {
    .Call('_armspp_arms', PACKAGE = 'armspp', xInitial, xl, xr, lpdf, convex, npoint, dometrop, xprev, arguments, nsamp, include_neval)
}

.arms2 <- function(nSamples, logPdf, lower, upper, initial, convex, maxPoints, metropolis, previous, arguments, includeNEvaluations) {
    .Call('_armspp_arms2', PACKAGE = 'armspp', nSamples, logPdf, lower, upper, initial, convex, maxPoints, metropolis, previous, arguments, includeNEvaluations)
}

