# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

.arms <- function(xinit, xl, xr, lpdf, convex, npoint, dometrop, xprev, nsamp, include_neval) {
    .Call('_armspp_arms', PACKAGE = 'armspp', xinit, xl, xr, lpdf, convex, npoint, dometrop, xprev, nsamp, include_neval)
}

